var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,e){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var k=a[g];if(d.call(e,k,g,a))return{i:g,v:k}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){a!=Array.prototype&&a!=Object.prototype&&(a[d]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,e,f){if(d){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in e||(e[g]={});e=e[g]}a=a[a.length-1];f=e[a];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})}};
(function(a){var d=function(a,b){if(a.neoWizeCounter>=global.domain.marketing.NeoWizeSettings.maxLoadAttempts-1)b();else if(a.neoWizeCounter++,window.Neowize&&window.Neowize.Events)window.Neowize.Events.register("neowize_ready",b);else return setTimeout(function(){d(a,b)},global.domain.marketing.NeoWizeSettings.loadAttemptDelay)},e=function(c){c=a('[data-type="receipt-box"]');var b=[];0<c.length&&(c=c.attr("data-receipt"),a('[data-type="product-item"]').each(function(){var c=a(this);b.push({id:c.attr("data-skunumber"),
price:Number(c.attr("data-price"))||0,quantity:Number(c.attr("data-qty"))||0})}),global.domain.marketing.initCriteoThankYouPage(c,b))},f=function(a,b){a=[];for(var c=0;c<b.orderItems.length;c++){var h=b.orderItems[c];a.push({name:h.name,id:h.SKUNumber,price:h.price,brand:"Waves",category:h.departmentName,quantity:h.quantity})}0<b.discount&&a.push({name:"Discount",price:-b.discount,brand:"Waves",quantity:1});window.dataLayer.push({event:"TransactionTrigger",PaymentMethod:b.fundSourceType,ecommerce:{purchase:{actionField:{id:b.receiptId,
affiliation:"Online Store",revenue:b.revenue,tax:b.tax,shipping:b.shipping,coupon:b.coupon},products:a}}})},g=function(a,b){if(window.ire){a={orderId:b.receiptId,customerId:b.receiptId,customerEmail:"",customerStatus:b.isNewCustomer?"New":"Returning",currencyCode:"USD",orderPromoCode:b.coupon,items:[]};if(b.orderItems)for(var c=0;c<b.orderItems.length;c++){var h=b.orderItems[c];a.items.push({subTotal:h.amount,category:h.departmentName,sku:h.SKUNumber,quantity:h.quantity})}window.ire("trackConversion",
10223,a,{verifySiteDefinitionMatch:!0});console.log("Impact Radius");console.log("--------------------------------");console.log(a)}},k=function(c){c=a("#json-hidden-data");var b={};0<c.length&&(b=a.parseJSON(a.trim(c.text())));return b},m=function(c){c=a(".waves-refer-friend-box");var b=300,d=300;b=0<a("#waves-user-email").length&&!!a("#waves-user-email").text();0<c.length&&b&&(0<a("#iphone-top-icons").length?(b="90%",d=600):(b=Number(c.attr("data-width"))||620,d=Number(c.attr("data-height"))||480),
a.colorbox({width:b,height:d,opacity:"0.6",overlayClose:!0,html:'<form action="#" id="rfr-form">'+c.html()+"</form>",fixed:!0,scrolling:!0,onComplete:function(){a("#colorbox form").validate({onsubmit:!1,errorPlacement:function(a,b){b.parents(".row").next(".row-error").html(a)}});a('#colorbox [data-validation-type="email"]').each(function(){a(this).rules("add",{required:!0,minlength:2,messages:{regex:global.domain.validation.emailMessage},regex:global.domain.validation.emailRegex})});a('#colorbox [data-validation-btn="true"]').off("click").on("click",
function(b){a("#colorbox form").valid()&&a(document).trigger("refer.send.email")})},escKey:!0,closeButton:!0}))},n=function(c){a(".refer-friend-widget").on("click",function(){m()});a(".refer-friend-widget a").on("click",function(a){a.preventDefault()})},p=function(c){c=a("#norton-link");c.replaceWith("<span>"+c.text()+"</span>");window.parent&&(window.parent.postMessage("InApp Purchase Thank You",a.trim(a("#domain").text())),console.log("InApp Purchase Thank You"));a("#back-inapp-link").on("click",
function(b){b.preventDefault();window.parent&&(window.parent.postMessage("InApp Purchase Back Button",a.trim(a("#domain").text())),console.log("InApp Purchase Back Button"))})};global.plugins.push({name:"thank-you",init:function(){var c={neoWizeCounter:0};if("true"!==a.trim(a("#is-china-enabled").text().toLowerCase())){if(0<a("#receipt-general-details").length){var b=k(c);b&&b.marketingScriptsEnabled&&(f(c,b),window.gdpr&&window.gdpr.isPerformance&&(g(c,b),c=this,d(c,function(){if(window.Neowize&&
window.Neowize.UserEvents){var a={grand_total:b.total,subtotal:b.subtotal,tax_amount:b.tax,shipping_amount:b.shipping,order_id:b.receiptId},c=[];if(b.orderItems)for(var d=0;d<b.orderItems.length;d++){var e=b.orderItems[d];c.push({unique_id:e.SKUNumber,quantity:e.quantity,unit_price:e.price})}window.Neowize.UserEvents.user_complete_checkout(c,a)}})))}window.gdpr&&window.gdpr.isMarketing&&e(this)}var l=Number(a.trim(a("#inapp-purchase-id-lit").text()))||0;0>=a("#iphone-top-icons").length&&0===l&&m(c);
0<l&&p(c);n(c)}})})(jQuery);
